language: cpp
sudo: required
dist: trusty
cache: ccache
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y
    automake gtk-doc-tools
    gobject-introspection
    libfftw3-dev libjpeg-turbo8-dev
    libpng12-dev libwebp-dev libtiff4-dev libxml2-dev
    swig libmagick++-dev bc
    libcfitsio3-dev libgsl0-dev libmatio-dev
    liborc-0.4-dev liblcms2-dev libpoppler-glib-dev
    librsvg2-dev libgif-dev
    libpango1.0-dev libgsf-1-dev libopenslide-dev
    python-dev python-gi-dev libgirepository1.0-dev
before_script:
  - ./bootstrap.sh
  - PYTHON=/usr/bin/python ./configure
  - make -j`nproc`
script:
  - VERBOSE=1 make check
