language: cpp
before_install:
  - sudo add-apt-repository ppa:lyrasis/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install automake gobject-introspection gtk-doc-tools 
  - sudo apt-get install libfftw3-dev libglib2.0-dev libjpeg-turbo8-dev 
  - sudo apt-get install libpng12-dev libwebp-dev libtiff4-dev libxml2-dev 
  - sudo apt-get install swig libmagick++-dev bc libgsf-1-dev 
  - sudo apt-get install libcfitsio3-dev libgsl0-dev libmatio-dev
  - sudo apt-get install liborc-0.4-dev liblcms2-dev libopenslide-dev
  - sudo apt-get install python-dev python3-dev 
  - sudo apt-get install python-gi-dev python3-gi python-gi-cairo
before_script:
  - ./bootstrap.sh
  - ./configure 
  - make
  - sudo make install
  - sudo ldconfig
  - sudo cp python/Vips.py /usr/lib/python2.7/dist-packages/gi/overrides
  - sudo cp python/Vips.py /usr/lib/python3/dist-packages/gi/overrides
script: 
  - make check
